# Generated by Django 3.1.1 on 2020-10-04 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('voltage', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('driven_distance', models.FloatField()),
                ('out_state_of_charge', models.FloatField()),
                ('in_state_of_charge', models.FloatField()),
                ('used_energy', models.FloatField()),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swap.attendant')),
                ('battery_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swap.battery')),
                ('battery_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_swaps', to='swap.battery')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swap.driver')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_swaps', to='swap.station')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('color', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swap.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attendant',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swap.station'),
        ),
        migrations.AddField(
            model_name='attendant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
